输入框前置协议选项，小视窗输入组件ui优化
halo-dev/halo-comment pull request #55
Opened 2021-06-28 08:24 UTC by DuQingsong2002

2021-06-28 08:42 UTC, JohnNiang commented
感谢你的 PR。

2021-06-28 09:30 UTC, JohnNiang commented
@DuQingsong2002 请问关闭 PR 的原因是什么？

2021-06-28 09:49 UTC, DuQingsong2002 commented
自动回复吗，，我看一个issus下面说要重写（https://github.com/halo-dev/halo-comment/issues/33#issuecomment-651782623），我这没啥意义了，
然后我这个不是没必要合并吗(It is not required to merge),,,,,,,纯github新手，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo-comment"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo-comment] 输入框前置协议选项，小视窗输入组件ui优化 (#55)





 
@DuQingsong2002 请问关闭 PR 的原因是什么？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-28 09:57 UTC, ruibaby commented
@DuQingsong2002 但这个仓库实际上我们是没有废弃的，我们并没有拒收 pr，那个提示应该是没有经过 review 或者没有合并前的提示，并不是我们给出的。我们会在 review 之后合并你的分支。

2021-06-28 15:36 UTC, ruibaby requested changes

2021-06-28 15:36 UTC, ruibaby commented on src/components/CommentEditor.vue
> +                  <label for="currentInput-nickname">
~~加上 label 的用途是？因为我看到你设置了 `display:none`~~

2021-06-28 15:36 UTC, ruibaby commented on src/components/CommentEditor.vue
> +                  <label for="currentInput-nickname">
不建议使用这样的方式进行移动端适配，你可以考虑在移动端设置为一行一个输入框。

2021-06-28 15:36 UTC, ruibaby commented on src/components/CommentEditor.vue
> +                    <!-- 网站协议下拉框, 就两个所以直接写了 -->
这个注释没有必要。

2021-06-28 15:36 UTC, ruibaby commented on src/components/CommentEditor.vue
> +    'urlInfo': {
没有必要，可以在提交的时候拼接。

2021-06-28 15:36 UTC, ruibaby commented on src/components/CommentEditor.vue
>              localStorage.setItem('comment-author', this.comment.author)
将评论者信息缓存的时候，你可能得修改一下，需要将 protocol 和 domain 分别存入。

2021-06-28 15:36 UTC, ruibaby commented
@DuQingsong2002 后续修改，直接 commit 然后 push 即可。会汇总到此 pr。

2021-07-11 11:30 UTC, ruibaby commented
@DuQingsong2002 有一个冲突需要解决一下。

2021-07-11 11:39 UTC, ruibaby commented
![image](https://user-images.githubusercontent.com/21301288/125193557-8b41c780-e27f-11eb-917d-8f7cf82649d2.png)

网址输入框似乎渲染异常了。

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'indexOf' of null"

found in

---> <CommentInput> at src/components/CommentInput.vue
       <CommentEditor> at src/components/CommentEditor.vue
         <Comment> at src/components/Comment.vue
           <App> at src/App.vue
             <Root>
```

```
TypeError: Cannot read property 'indexOf' of null
    at VueComponent.suggestionListHandle (CommentInput.vue?238c:43)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4597)
    at VueComponent.computedGetter [as suggestionListHandle] (vue.runtime.esm.js?2b0e:4851)
    at Object.get (vue.runtime.esm.js?2b0e:2081)
    at Proxy.render (CommentInput.vue?287c:14)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3569)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4081)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495)
    at new Watcher (vue.runtime.esm.js?2b0e:4484)
```

2021-07-18 08:59 UTC, ruibaby approved these changes

2021-07-18 08:59 UTC, merged